# backend/api/deps.py

import logging
import os
from typing import Any, Callable, Dict, NamedTuple, Optional, Union

from fastapi import (
    Depends,
    Header,
    HTTPException,
    Query,
    WebSocket,
    WebSocketException,
    status,
)
from fastapi.security import OAuth2PasswordBearer

from backend.core.config import settings

logger = logging.getLogger(__name__)

# OAuth2 스키마 정의
oauth2_scheme = OAuth2PasswordBearer(tokenUrl="token")

# [Security] Mock User Definitions (Centralized)
# Separate mocks for different roles to detect permission issues in dev environment.
MOCK_ADMIN_USER: Dict[str, Any] = {"username": "dev_admin", "id": 1, "role": "admin"}
MOCK_REGULAR_USER: Dict[str, Any] = {"username": "dev_user", "id": 2, "role": "user"}

# Note: 'MOCK_USER' alias has been removed to enforce explicit role usage.


def _ensure_dev_environment(
    exception_factory: Callable[[], Union[HTTPException, WebSocketException]],
) -> None:
    """
    Blocks mock-based authentication outside of local/development environments.

    This acts as a security guard to prevent mock credentials or bypasses
    from being evaluated in a staging or production deployment.

    Args:
        exception_factory: A callable returning the exception to raise.
            Using a factory prevents premature instantiations of the exceptions.

    Raises:
        HTTPException | WebSocketException: The exception generated by the factory
            if the environment is not 'local' or 'development'.
    """
    # Note: Accessing os.getenv directly as config module doesn't expose ENVIRONMENT yet.
    # TODO: Route this through backend.config.AppConfig when available.
    env = os.getenv("ENVIRONMENT", "production")
    if env not in ["local", "development"]:
        raise exception_factory()


def get_current_user(token: str = Depends(oauth2_scheme)) -> Dict[str, Any]:
    """
    Dependency to retrieve the current authenticated user for HTTP requests.

    In development and local environments, this returns a mock admin user
    to facilitate testing and system operations. Production usage is currently
    blocked until authorization logic is implemented.

    Args:
        token (str): The OAuth2 access token provided in the Authorization header.

    Returns:
        Dict[str, Any]: A dictionary containing user information (username, id, role).

    Raises:
        HTTPException: 501 Not Implemented if called in a non-dev (production) environment.
    """
    # Default behavior: 501 Not Implemented in production
    _ensure_dev_environment(
        lambda: HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="Authentication Logic is not yet implemented for production.",
        )
    )

    # TODO: [Phase 2] verify_token(token)

    return MOCK_ADMIN_USER


async def get_current_user_ws(
    websocket: WebSocket, token: Optional[str] = Query(None)
) -> Dict[str, Any]:
    """
    Dependency to retrieve the current authenticated user for WebSocket connections.

    Checks the token query parameter. In local and development environments,
    it returns a mock regular user to test standard access controls.

    Args:
        websocket (WebSocket): The WebSocket connection object.
        token (Optional[str]): The authentication token extracted from the query parameters.

    Returns:
        Dict[str, Any]: A dictionary containing user information (username, id, role).

    Raises:
        WebSocketException:
            - Close code 1008 (Policy Violation) if the token is missing.
            - Close code 1008 if called in a non-dev (production) environment.
    """
    if token is None:
        # Strictly reject missing tokens with WebSocket Close Code 1008 (Policy Violation)
        raise WebSocketException(
            code=status.WS_1008_POLICY_VIOLATION,
            reason="Missing authentication token via query parameter",
        )

    # Use WebSocketException for environment guard as well
    _ensure_dev_environment(
        lambda: WebSocketException(
            code=status.WS_1008_POLICY_VIOLATION, reason="Auth not implemented"
        )
    )

    # TODO: [Phase 2] Verify token logic

    return MOCK_REGULAR_USER


class LanguageEntry(NamedTuple):
    """
    Represents a single parsed Accept-Language header entry.

    Attributes:
        full_tag (str): The full language code (e.g., 'en-US').
        primary_tag (str): The primary language subtag (e.g., 'en').
        q_value (float): The quality value (weight) indicating preference, range [0.0, 1.0].
    """
    full_tag: str
    primary_tag: str
    q_value: float


def _parse_language_entry(part: str) -> Optional[LanguageEntry]:
    """
    Parses a single Accept-Language entry into a LanguageEntry.

    Parses parameters such as quality factors ('q=0.8') and extracts the
    primary language subtag. Wildcard '*' values are ignored to enforce
    concrete language matching.

    Args:
        part (str): A segment from the Accept-Language header (e.g., 'ko-KR;q=0.9').

    Returns:
        Optional[LanguageEntry]: The parsed LanguageEntry, or None if the entry is malformed,
            empty, or represents a wildcard.
    """
    part = part.strip()
    if not part:
        return None

    # Split off parameters, e.g. "en-US;q=0.8;v=1" -> ["en-US", "q=0.8", "v=1"]
    segments = [s.strip() for s in part.split(";") if s.strip()]
    if not segments:
        return None

    lang = segments[0]

    # Explicitly ignore wildcard '*' as we require concrete supported languages
    if lang == "*":
        return None

    params = segments[1:]
    q_value = 1.0

    for param in params:
        # Check for q-factor parameter
        if param.lower().startswith("q="):
            try:
                parts = param.split("=", 1)
                if len(parts) != 2:
                    return None  # Malformed q-parameter

                raw_q = parts[1].strip()
                if not raw_q:
                    return None  # Empty value

                parsed_q = float(raw_q)
                # RFC 7231: q-value must be in range [0.0, 1.0]
                if 0.0 <= parsed_q <= 1.0:
                    q_value = parsed_q
                    break  # Valid q found, stop scanning parameters
                else:
                    return None  # Out of range
            except ValueError:
                return None  # Parsing failed

    # Normalize: "en-US" -> "en"
    if not (primary_lang := lang.split("-")[0].strip()):
        return None

    return LanguageEntry(full_tag=lang, primary_tag=primary_lang, q_value=q_value)


def normalize_locale(locale: Optional[str]) -> Optional[str]:
    """
    Normalizes a locale string by stripping whitespace and converting to lowercase.

    Args:
        locale (Optional[str]): The raw locale string to normalize.

    Returns:
        Optional[str]: The normalized lowercase locale string, or None if the input is empty or None.
    """
    return locale.strip().lower() if locale else None


def extract_locale_from_header(accept_language: Optional[str]) -> str:
    """
    Extracts and resolves the best matching locale from the Accept-Language header.

    Parses the header, orders the locales by their quality factor (q-value) in
    descending order, and returns the first locale that is supported by the application.
    If no matches are found, it falls back to the default locale.

    Args:
        accept_language (Optional[str]): The raw Accept-Language header value from the client.

    Returns:
        str: The matched supported locale (e.g., "ko", "en") or the default locale.
    """
    if not accept_language:
        return settings.DEFAULT_LOCALE

    # Parse all language entries and build a map: primary_tag -> highest q_value
    lang_map: Dict[str, float] = {}
    for part in accept_language.split(","):
        entry = _parse_language_entry(part)
        if not entry:
            continue

        # Keep only the highest q-value for each primary language
        if (
            entry.primary_tag not in lang_map
            or entry.q_value > lang_map[entry.primary_tag]
        ):
            lang_map[entry.primary_tag] = entry.q_value

    if not lang_map:
        logger.debug(
            "Empty lang_map for header '%s'. Falling back to default.", accept_language
        )
        return settings.DEFAULT_LOCALE

    # Sort by q-value (descending) and find first supported locale
    sorted_langs = sorted(lang_map.items(), key=lambda x: x[1], reverse=True)
    for lang, _ in sorted_langs:
        if lang in settings.SUPPORTED_LOCALES:
            return lang

    # Fallback to default if no supported locale found
    logger.debug(
        "No supported locale found in '%s'. Falling back to default.", accept_language
    )
    return settings.DEFAULT_LOCALE


def get_locale(
    accept_language: Optional[str] = Header(default=None, alias="Accept-Language")
) -> str:
    """
    FastAPI dependency to extract and resolve the locale from the Accept-Language header.

    This wraps `extract_locale_from_header` to automatically inject the resolved
    locale string into route handlers.

    Args:
        accept_language (Optional[str]): The Accept-Language header value injected by FastAPI.

    Returns:
        str: The resolved locale string.
    """
    return extract_locale_from_header(accept_language)

