# backend/schemas/streaming.py

from typing import Annotated, Literal, Union
from pydantic import BaseModel, Field


class TokenChunk(BaseModel):
    """
    Represents a single text token generated by the model.
    """

    type: Literal["token"] = "token"
    data: str = Field(..., description="The text content of the token.")


class DoneChunk(BaseModel):
    """
    Represents the end of the stream.
    """

    type: Literal["done"] = "done"
    data: Literal[""] = Field(
        default="",
        description="Empty string indicating the stream has successfully completed.",
    )


class ErrorChunk(BaseModel):
    """
    Represents an error that occurred during streaming.
    WARNING: The `message` field MUST be masked using `mask_pii_id()`
    before instantiation to prevent PII leakage.
    """

    type: Literal["error"] = "error"
    code: str = Field(..., description="Error code identifier.")
    message: str = Field(
        ..., description="Error message. Must be masked to protect PII."
    )


# Discriminated Union for OpenAPI generation (SSOT for frontend sync)
StreamChunk = Annotated[
    Union[TokenChunk, DoneChunk, ErrorChunk],
    Field(discriminator="type", description="Streaming chunk variants."),
]
