# backend/schemas/streaming.py

from enum import Enum
from typing import Annotated, Literal, Union
from pydantic import BaseModel, Field, field_validator

from backend.utils.common import mask_pii_id


class StreamChunkType(str, Enum):
    """
    Centralized discriminator values for StreamChunk variants.
    """
    TOKEN = "token"
    DONE = "done"
    ERROR = "error"


class TokenChunk(BaseModel):
    """
    Represents a single text token generated by the model.
    """

    type: Literal[StreamChunkType.TOKEN] = StreamChunkType.TOKEN
    data: str = Field(..., description="The text content of the token.")


class DoneChunk(BaseModel):
    """
    Represents the end of the stream.
    """

    type: Literal[StreamChunkType.DONE] = StreamChunkType.DONE
    data: Literal[""] = Field(
        default="",
        description="Empty string indicating the stream has successfully completed.",
    )


class ErrorChunk(BaseModel):
    """
    Represents an error that occurred during streaming.
    The `message` field is automatically masked by Pydantic validators
    to prevent PII leakage.
    """

    type: Literal[StreamChunkType.ERROR] = StreamChunkType.ERROR
    code: str = Field(..., description="Error code identifier.")
    message: str = Field(
        ..., description="Error message. Automatically masked to protect PII."
    )

    @field_validator("message")
    @classmethod
    def ensure_pii_masked(cls, v: str) -> str:
        """
        Enforce PII masking at the schema validation level.
        Even if unmasked data is passed during instantiation,
        this validator guarantees it will be masked before serialization.
        """
        return mask_pii_id(v)


# Discriminated Union for OpenAPI generation (SSOT for frontend sync)
StreamChunk = Annotated[
    Union[TokenChunk, DoneChunk, ErrorChunk],
    Field(discriminator="type", description="Streaming chunk variants."),
]
